Redirect if source not absolute URL
ome/omero-web-zarr pull request #6
Opened 2023-02-10 12:36 UTC by will-moore

Fixes open-with vizarr.

Vizarr requires that the `?source=path/to/image.zarr` parameter is an absolute URL.
With "Open-with" functionality, JavaScript that generates the link doesn't have the absolute URL, so this uses python code to fix that.
This is more reliable that using JavaScript to guess the absolute URL since we don't know what page it is running on (e.g. in figure).

To test:
 - Try Open with... vizarr

2023-02-10 14:04 UTC, pwalczysko commented
> Try Open with... vizarr

Tried that on merge-ci. Open with vizarr works, but all I get (on some 10 different images) always a black image in vizarr.

2023-02-10 14:05 UTC, pwalczysko requested changes
Please comment on the blackness of images in vizarr

2023-02-13 21:28 UTC, will-moore commented
@pwalczysko should be on merge-ci tomorrow

2023-02-16 17:16 UTC, will-moore commented
Closing since this will conflict with #7. Redirect logic is now added there.

2023-02-16 17:16 UTC, closed without merging